### ISSUE TITLE
Youtube Steam/Bulk download

### ISSUE THREAD

**Issue by CallMeYuuuu** [Geoxor/Amethyst#374]
**Describe the idea you'd like for Amethyst to have**
A way to stream from youtube/soundcloud or a way to bulk download songs/a playlist from youtube

**Comment by Geoxor** [comment]
this idea kinda goes beyond what amethyst is meant to be but maybe later on

**Comment by otiskujawa** [comment]
It may be option to add music from link/directory, then made it able to get file from http, https, local.
`/mnt/hdd/music/file.mp3` - add file
`C:/Users/otiskujawa/Music` - add directory
`https://cdn.discordapp.com/attachments/667464431562653706/897835325555097630/Hatsune_Miku_-_World_is_Mine_Geoxor_Remix.flac` - add remote file
`http://gobota.lan/file.mp3` - http remote file
Then maybe youtube, smb and ftp (anonymous only because logging in is propably hard)
