### ISSUE TITLE
Using the windowed mode toggle button while in the node editor breaks zoom until the window is maximized while in the queue view.

### ISSUE THREAD

**Issue by okawaffles** [Geoxor/Amethyst#553]
**Describe the bug**
When you are on the node viewing/editing area, and you set the window to windowed mode using the button in the top right, the zoom will be reset to default until you move the maximize window in the queue view.

**Amethyst Details (required):**
 - Version [e.g. v1.9.10]
 - Windows 11

**To Reproduce (optional)**
1. Maximize the window, set the zoom to something other than default.
2. Select the node editor on the left hand side.
3. Use the top-right windowed-mode button to set the window to windowed mode.
4. The zoom will be set to default until the window is maximized, but only when you're in the queue area.

**Expected behavior (optional)**
The zoom should stay as is, regardless of windowed mode or not.

**Screenshots (optional)**
![Video of the bug happening](https://okayu.okawaffles.com/content/okawaffles/amethyst-zoom-broken.mp4)

**Additional context (optional)**
This bug also appears to happen while on the settings menu.

**Comment by okawaffles** [comment]
The bug is not present when I run Amethyst from `yarn dev` so it might already be fixed..?

**Comment by Geoxor** [comment]
I've had this bug mentioned before, and i believe it was because i was changing `webFrame.setZoomFactor()`, it might have been a bug with electron/chromium

Just tested it and indeed it seems to work fine with `yarn dev` but not when built, I hate these production-only issues, ill look more into it
https://github.com/Geoxor/Amethyst/assets/34042825/06f0022a-86fd-4eda-b4dc-d8e1212c8a3f

**Comment by Geoxor** [comment]
Indeed chromium (i assume) is doing some sort of page-level caching instead of using the same zoom level for the entire domain

https://github.com/Geoxor/Amethyst/assets/34042825/3030e12a-9add-4f7a-856c-b3336c9d2093

**Comment by okawaffles** [comment]
Interesting. Does the dev build use a different Chromium than production?

**Comment by Geoxor** [comment]
Just saw this note on the webContents.setZoomLevel() 

![image](https://github.com/Geoxor/Amethyst/assets/34042825/e953a7cd-261e-4507-974b-b8586f6f463f)

**Comment by Geoxor** [comment]
> Interesting. Does the dev build use a different Chromium than production?

Not that I am aware of, maybe vue-router works differently on prod than dev

**Comment by Geoxor** [comment]
Here's the window.location.href 

production:
![image](https://github.com/Geoxor/Amethyst/assets/34042825/24c9a0ba-4a40-44e9-81c0-d41da65e81c2)

dev:
![image](https://github.com/Geoxor/Amethyst/assets/34042825/aef3164f-02e5-4ade-9aea-552a9a0f0d91)

Honestly not sure what exactly the cause is by it may be due to it being different file:// paths that it treats it as not same-origin

**Comment by Geoxor** [comment]
![image](https://github.com/Geoxor/Amethyst/assets/34042825/074c13b5-5e76-489e-911c-73e8a79c49ac)
